// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WattsOn.Infrastructure.Persistence;

#nullable disable

namespace WattsOn.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WattsOnDbContext))]
    [Migration("20260218035230_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AfregningFaktura", b =>
                {
                    b.Property<Guid>("AfregningerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FakturaId")
                        .HasColumnType("uuid");

                    b.HasKey("AfregningerId", "FakturaId");

                    b.HasIndex("FakturaId");

                    b.ToTable("faktura_afregninger", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Afregning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCorrection")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correction");

                    b.Property<Guid>("LeveranceId")
                        .HasColumnType("uuid")
                        .HasColumnName("leverance_id");

                    b.Property<Guid>("MålepunktId")
                        .HasColumnType("uuid")
                        .HasColumnName("målepunkt_id");

                    b.Property<Guid?>("PreviousAfregningId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_afregning_id");

                    b.Property<Guid>("TidsserieId")
                        .HasColumnType("uuid")
                        .HasColumnName("tidsserie_id");

                    b.Property<int>("TidsserieVersion")
                        .HasColumnType("integer")
                        .HasColumnName("tidsserie_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LeveranceId");

                    b.HasIndex("MålepunktId");

                    b.HasIndex("TidsserieId");

                    b.ToTable("afregninger", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.AfregningLinje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AfregningId")
                        .HasColumnType("uuid")
                        .HasColumnName("afregning_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("PrisId")
                        .HasColumnType("uuid")
                        .HasColumnName("pris_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AfregningId");

                    b.ToTable("afregning_linjer", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Aktør", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsOwn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_own");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("aktører", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Faktura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sent");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("KundeId")
                        .HasColumnType("uuid")
                        .HasColumnName("kunde_id");

                    b.Property<Guid?>("OriginalFakturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_faktura_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("KundeId");

                    b.HasIndex("OriginalFakturaId");

                    b.ToTable("fakturaer", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.FakturaLinje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AfregningLinjeId")
                        .HasColumnType("uuid")
                        .HasColumnName("afregning_linje_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("FakturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("faktura_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FakturaId");

                    b.ToTable("faktura_linjer", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Kunde", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("kunder", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Leverance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AktørId")
                        .HasColumnType("uuid")
                        .HasColumnName("aktør_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_process_id");

                    b.Property<Guid?>("EndedByProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("ended_by_process_id");

                    b.Property<Guid>("KundeId")
                        .HasColumnType("uuid")
                        .HasColumnName("kunde_id");

                    b.Property<Guid>("MålepunktId")
                        .HasColumnType("uuid")
                        .HasColumnName("målepunkt_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AktørId");

                    b.HasIndex("KundeId");

                    b.HasIndex("MålepunktId");

                    b.ToTable("leverancer", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Målepunkt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Art")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("art");

                    b.Property<string>("ConnectionState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("connection_state");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GridArea")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grid_area");

                    b.Property<bool>("HasActiveSupply")
                        .HasColumnType("boolean")
                        .HasColumnName("has_active_supply");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("resolution");

                    b.Property<string>("SettlementMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("settlement_method");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("målepunkter", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("quality");

                    b.Property<Guid>("TidsserieId")
                        .HasColumnType("uuid")
                        .HasColumnName("tidsserie_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TidsserieId", "Timestamp");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Pris", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChargeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("charge_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("PriceResolution")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("price_resolution");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("VatExempt")
                        .HasColumnType("boolean")
                        .HasColumnName("vat_exempt");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId");

                    b.ToTable("priser", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.PrisPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("price");

                    b.Property<Guid>("PrisId")
                        .HasColumnType("uuid")
                        .HasColumnName("pris_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PrisId", "Timestamp");

                    b.ToTable("pris_points", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Pristilknytning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MålepunktId")
                        .HasColumnType("uuid")
                        .HasColumnName("målepunkt_id");

                    b.Property<Guid>("PrisId")
                        .HasColumnType("uuid")
                        .HasColumnName("pris_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MålepunktId");

                    b.HasIndex("PrisId");

                    b.ToTable("pristilknytninger", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Tidsserie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_latest");

                    b.Property<Guid>("MålepunktId")
                        .HasColumnType("uuid")
                        .HasColumnName("målepunkt_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("resolution");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("MålepunktId", "IsLatest");

                    b.ToTable("tidsserier", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessProcess")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("business_process");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_processed");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("processing_attempts");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("processing_error");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ReceiverGln")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("receiver_gln");

                    b.Property<string>("SenderGln")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("sender_gln");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsProcessed");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessProcess")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("business_process");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sent");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("ReceiverGln")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("receiver_gln");

                    b.Property<string>("Response")
                        .HasColumnType("jsonb")
                        .HasColumnName("response");

                    b.Property<DateTimeOffset?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<int>("SendAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("send_attempts");

                    b.Property<string>("SendError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("send_error");

                    b.Property<string>("SenderGln")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("sender_gln");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsSent");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Processes.BrsProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_state");

                    b.Property<DateTimeOffset?>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("ProcessData")
                        .HasColumnType("jsonb")
                        .HasColumnName("process_data");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("process_type");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId");

                    b.ToTable("brs_processes", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Processes.ProcessStateTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("from_state");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("to_state");

                    b.Property<DateTimeOffset>("TransitionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transitioned_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("process_state_transitions", (string)null);
                });

            modelBuilder.Entity("AfregningFaktura", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Afregning", null)
                        .WithMany()
                        .HasForeignKey("AfregningerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WattsOn.Domain.Entities.Faktura", null)
                        .WithMany()
                        .HasForeignKey("FakturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Afregning", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Leverance", "Leverance")
                        .WithMany()
                        .HasForeignKey("LeveranceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WattsOn.Domain.Entities.Målepunkt", "Målepunkt")
                        .WithMany()
                        .HasForeignKey("MålepunktId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WattsOn.Domain.Entities.Tidsserie", "Tidsserie")
                        .WithMany()
                        .HasForeignKey("TidsserieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "SettlementPeriod", b1 =>
                        {
                            b1.Property<Guid>("AfregningId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("settlement_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("settlement_start");

                            b1.HasKey("AfregningId");

                            b1.ToTable("afregninger");

                            b1.WithOwner()
                                .HasForeignKey("AfregningId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("AfregningId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("DKK")
                                .HasColumnName("total_currency");

                            b1.HasKey("AfregningId");

                            b1.ToTable("afregninger");

                            b1.WithOwner()
                                .HasForeignKey("AfregningId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.EnergyQuantity", "TotalEnergy", b1 =>
                        {
                            b1.Property<Guid>("AfregningId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasDefaultValue("kWh")
                                .HasColumnName("total_energy_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("total_energy_kwh");

                            b1.HasKey("AfregningId");

                            b1.ToTable("afregninger");

                            b1.WithOwner()
                                .HasForeignKey("AfregningId");
                        });

                    b.Navigation("Leverance");

                    b.Navigation("Målepunkt");

                    b.Navigation("SettlementPeriod")
                        .IsRequired();

                    b.Navigation("Tidsserie");

                    b.Navigation("TotalAmount")
                        .IsRequired();

                    b.Navigation("TotalEnergy")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.AfregningLinje", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Afregning", null)
                        .WithMany("Lines")
                        .HasForeignKey("AfregningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("AfregningLinjeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("DKK")
                                .HasColumnName("amount_currency");

                            b1.HasKey("AfregningLinjeId");

                            b1.ToTable("afregning_linjer");

                            b1.WithOwner()
                                .HasForeignKey("AfregningLinjeId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.EnergyQuantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("AfregningLinjeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasDefaultValue("kWh")
                                .HasColumnName("quantity_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("quantity_kwh");

                            b1.HasKey("AfregningLinjeId");

                            b1.ToTable("afregning_linjer");

                            b1.WithOwner()
                                .HasForeignKey("AfregningLinjeId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Aktør", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.CvrNumber", "Cvr", b1 =>
                        {
                            b1.Property<Guid>("AktørId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("cvr");

                            b1.HasKey("AktørId");

                            b1.ToTable("aktører");

                            b1.WithOwner()
                                .HasForeignKey("AktørId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.GlnNumber", "Gln", b1 =>
                        {
                            b1.Property<Guid>("AktørId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("character varying(13)")
                                .HasColumnName("gln");

                            b1.HasKey("AktørId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("aktører");

                            b1.WithOwner()
                                .HasForeignKey("AktørId");
                        });

                    b.Navigation("Cvr");

                    b.Navigation("Gln")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Faktura", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Kunde", "Kunde")
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WattsOn.Domain.Entities.Faktura", "OriginalFaktura")
                        .WithMany()
                        .HasForeignKey("OriginalFakturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "InvoicePeriod", b1 =>
                        {
                            b1.Property<Guid>("FakturaId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("invoice_period_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("invoice_period_start");

                            b1.HasKey("FakturaId");

                            b1.ToTable("fakturaer");

                            b1.WithOwner()
                                .HasForeignKey("FakturaId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Money", "SubTotal", b1 =>
                        {
                            b1.Property<Guid>("FakturaId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("sub_total");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("DKK")
                                .HasColumnName("sub_total_currency");

                            b1.HasKey("FakturaId");

                            b1.ToTable("fakturaer");

                            b1.WithOwner()
                                .HasForeignKey("FakturaId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Money", "Total", b1 =>
                        {
                            b1.Property<Guid>("FakturaId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("DKK")
                                .HasColumnName("total_currency");

                            b1.HasKey("FakturaId");

                            b1.ToTable("fakturaer");

                            b1.WithOwner()
                                .HasForeignKey("FakturaId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Money", "Vat", b1 =>
                        {
                            b1.Property<Guid>("FakturaId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("vat");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("DKK")
                                .HasColumnName("vat_currency");

                            b1.HasKey("FakturaId");

                            b1.ToTable("fakturaer");

                            b1.WithOwner()
                                .HasForeignKey("FakturaId");
                        });

                    b.Navigation("InvoicePeriod")
                        .IsRequired();

                    b.Navigation("Kunde");

                    b.Navigation("OriginalFaktura");

                    b.Navigation("SubTotal")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();

                    b.Navigation("Vat")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.FakturaLinje", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Faktura", null)
                        .WithMany("Lines")
                        .HasForeignKey("FakturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("FakturaLinjeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("DKK")
                                .HasColumnName("amount_currency");

                            b1.HasKey("FakturaLinjeId");

                            b1.ToTable("faktura_linjer");

                            b1.WithOwner()
                                .HasForeignKey("FakturaLinjeId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.EnergyQuantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("FakturaLinjeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasDefaultValue("kWh")
                                .HasColumnName("quantity_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("quantity_kwh");

                            b1.HasKey("FakturaLinjeId");

                            b1.ToTable("faktura_linjer");

                            b1.WithOwner()
                                .HasForeignKey("FakturaLinjeId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Quantity");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Kunde", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("KundeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("building_number");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city_name");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("Floor")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("floor");

                            b1.Property<string>("MunicipalityCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("municipality_code");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("post_code");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street_name");

                            b1.Property<string>("Suite")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("suite");

                            b1.HasKey("KundeId");

                            b1.ToTable("kunder");

                            b1.WithOwner()
                                .HasForeignKey("KundeId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.CvrNumber", "Cvr", b1 =>
                        {
                            b1.Property<Guid>("KundeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("cvr");

                            b1.HasKey("KundeId");

                            b1.ToTable("kunder");

                            b1.WithOwner()
                                .HasForeignKey("KundeId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.CprNumber", "Cpr", b1 =>
                        {
                            b1.Property<Guid>("KundeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("cpr");

                            b1.HasKey("KundeId");

                            b1.ToTable("kunder");

                            b1.WithOwner()
                                .HasForeignKey("KundeId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Cpr");

                    b.Navigation("Cvr");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Leverance", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Aktør", "Aktør")
                        .WithMany()
                        .HasForeignKey("AktørId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WattsOn.Domain.Entities.Kunde", "Kunde")
                        .WithMany("Leverancer")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WattsOn.Domain.Entities.Målepunkt", "Målepunkt")
                        .WithMany("Leverancer")
                        .HasForeignKey("MålepunktId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "SupplyPeriod", b1 =>
                        {
                            b1.Property<Guid>("LeveranceId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("supply_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("supply_start");

                            b1.HasKey("LeveranceId");

                            b1.ToTable("leverancer");

                            b1.WithOwner()
                                .HasForeignKey("LeveranceId");
                        });

                    b.Navigation("Aktør");

                    b.Navigation("Kunde");

                    b.Navigation("Målepunkt");

                    b.Navigation("SupplyPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Målepunkt", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("MålepunktId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("building_number");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city_name");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("Floor")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("floor");

                            b1.Property<string>("MunicipalityCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("municipality_code");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("post_code");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street_name");

                            b1.Property<string>("Suite")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("suite");

                            b1.HasKey("MålepunktId");

                            b1.ToTable("målepunkter");

                            b1.WithOwner()
                                .HasForeignKey("MålepunktId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.GlnNumber", "GridCompanyGln", b1 =>
                        {
                            b1.Property<Guid>("MålepunktId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("character varying(13)")
                                .HasColumnName("grid_company_gln");

                            b1.HasKey("MålepunktId");

                            b1.ToTable("målepunkter");

                            b1.WithOwner()
                                .HasForeignKey("MålepunktId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Gsrn", "Gsrn", b1 =>
                        {
                            b1.Property<Guid>("MålepunktId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(18)
                                .HasColumnType("character varying(18)")
                                .HasColumnName("gsrn");

                            b1.HasKey("MålepunktId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("målepunkter");

                            b1.WithOwner()
                                .HasForeignKey("MålepunktId");
                        });

                    b.Navigation("Address");

                    b.Navigation("GridCompanyGln")
                        .IsRequired();

                    b.Navigation("Gsrn")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Observation", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Tidsserie", null)
                        .WithMany("Observations")
                        .HasForeignKey("TidsserieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.EnergyQuantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("ObservationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasDefaultValue("kWh")
                                .HasColumnName("quantity_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("quantity_kwh");

                            b1.HasKey("ObservationId");

                            b1.ToTable("observations");

                            b1.WithOwner()
                                .HasForeignKey("ObservationId");
                        });

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Pris", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.GlnNumber", "OwnerGln", b1 =>
                        {
                            b1.Property<Guid>("PrisId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("character varying(13)")
                                .HasColumnName("owner_gln");

                            b1.HasKey("PrisId");

                            b1.ToTable("priser");

                            b1.WithOwner()
                                .HasForeignKey("PrisId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "ValidityPeriod", b1 =>
                        {
                            b1.Property<Guid>("PrisId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_to");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_from");

                            b1.HasKey("PrisId");

                            b1.ToTable("priser");

                            b1.WithOwner()
                                .HasForeignKey("PrisId");
                        });

                    b.Navigation("OwnerGln")
                        .IsRequired();

                    b.Navigation("ValidityPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.PrisPoint", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Pris", null)
                        .WithMany("PricePoints")
                        .HasForeignKey("PrisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Pristilknytning", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Målepunkt", "Målepunkt")
                        .WithMany()
                        .HasForeignKey("MålepunktId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WattsOn.Domain.Entities.Pris", "Pris")
                        .WithMany()
                        .HasForeignKey("PrisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "LinkPeriod", b1 =>
                        {
                            b1.Property<Guid>("PristilknytningId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("link_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("link_start");

                            b1.HasKey("PristilknytningId");

                            b1.ToTable("pristilknytninger");

                            b1.WithOwner()
                                .HasForeignKey("PristilknytningId");
                        });

                    b.Navigation("LinkPeriod")
                        .IsRequired();

                    b.Navigation("Målepunkt");

                    b.Navigation("Pris");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Tidsserie", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Målepunkt", "Målepunkt")
                        .WithMany("Tidsserier")
                        .HasForeignKey("MålepunktId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "Period", b1 =>
                        {
                            b1.Property<Guid>("TidsserieId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_start");

                            b1.HasKey("TidsserieId");

                            b1.ToTable("tidsserier");

                            b1.WithOwner()
                                .HasForeignKey("TidsserieId");
                        });

                    b.Navigation("Målepunkt");

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Processes.BrsProcess", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.GlnNumber", "CounterpartGln", b1 =>
                        {
                            b1.Property<Guid>("BrsProcessId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("character varying(13)")
                                .HasColumnName("counterpart_gln");

                            b1.HasKey("BrsProcessId");

                            b1.ToTable("brs_processes");

                            b1.WithOwner()
                                .HasForeignKey("BrsProcessId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Gsrn", "MålepunktGsrn", b1 =>
                        {
                            b1.Property<Guid>("BrsProcessId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(18)
                                .HasColumnType("character varying(18)")
                                .HasColumnName("målepunkt_gsrn");

                            b1.HasKey("BrsProcessId");

                            b1.ToTable("brs_processes");

                            b1.WithOwner()
                                .HasForeignKey("BrsProcessId");
                        });

                    b.Navigation("CounterpartGln");

                    b.Navigation("MålepunktGsrn");
                });

            modelBuilder.Entity("WattsOn.Domain.Processes.ProcessStateTransition", b =>
                {
                    b.HasOne("WattsOn.Domain.Processes.BrsProcess", null)
                        .WithMany("Transitions")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Afregning", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Faktura", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Kunde", b =>
                {
                    b.Navigation("Leverancer");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Målepunkt", b =>
                {
                    b.Navigation("Leverancer");

                    b.Navigation("Tidsserier");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Pris", b =>
                {
                    b.Navigation("PricePoints");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Tidsserie", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("WattsOn.Domain.Processes.BrsProcess", b =>
                {
                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
