-- Run this on AXDB50 to see all columns on the rate and price tables
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('EXU_PRICEELEMENTTABLE', 'EXU_PRICEELEMENTRATES', 'EXU_PRICEELEMENTCHECKDATA')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- Check what makes CD tariff rate rows unique
SELECT TOP 20 *
FROM EXU_PRICEELEMENTRATES
WHERE DATAAREAID = 'ER' AND PARTYCHARGETYPEID = 'CD' AND CHARGETYPECODE = 3
  AND STARTDATE >= '2024-01-01'
ORDER BY STARTDATE, RECID;
