// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WattsOn.Infrastructure.Persistence;

#nullable disable

namespace WattsOn.Infrastructure.Migrations
{
    [DbContext(typeof(WattsOnDbContext))]
    [Migration("20260220083158_PricingModelAndMarginValidFrom")]
    partial class PricingModelAndMarginValidFrom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WattsOn.Domain.Entities.AggregatedObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregatedTimeSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregated_time_series_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Kwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("kwh");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AggregatedTimeSeriesId");

                    b.ToTable("aggregated_observations", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.AggregatedTimeSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("business_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GridArea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grid_area");

                    b.Property<string>("MeteringPointType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metering_point_type");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quality_status");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("resolution");

                    b.Property<string>("SettlementMethod")
                        .HasColumnType("text")
                        .HasColumnName("settlement_method");

                    b.Property<decimal>("TotalEnergyKwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("total_energy_kwh");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("aggregated_time_series", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("SupplierIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_identity_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SupplierIdentityId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.MeteringPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Art")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("art");

                    b.Property<string>("ConnectionState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("connection_state");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GridArea")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grid_area");

                    b.Property<bool>("HasActiveSupply")
                        .HasColumnType("boolean")
                        .HasColumnName("has_active_supply");

                    b.Property<bool>("HasElectricalHeating")
                        .HasColumnType("boolean")
                        .HasColumnName("has_electrical_heating");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("resolution");

                    b.Property<string>("SettlementMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("settlement_method");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("metering_points", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Observation", b =>
                {
                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("quality");

                    b.Property<Guid>("TimeSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_series_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Timestamp", "Id");

                    b.HasIndex("TimeSeriesId", "Timestamp");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<string>("ChargeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("charge_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPassThrough")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pass_through");

                    b.Property<bool>("IsTax")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tax");

                    b.Property<string>("PriceResolution")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("price_resolution");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("VatExempt")
                        .HasColumnType("boolean")
                        .HasColumnName("vat_exempt");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId");

                    b.ToTable("prices", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.PriceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MeteringPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("metering_point_id");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("pris_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MeteringPointId");

                    b.HasIndex("PriceId");

                    b.ToTable("price_links", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.PricePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("price");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("pris_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PriceId", "Timestamp");

                    b.ToTable("price_points", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.ReconciliationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChargeId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("charge_id");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("charge_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DataHubAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("datahub_amount");

                    b.Property<decimal>("Difference")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("difference");

                    b.Property<decimal>("OurAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("our_amount");

                    b.Property<Guid>("ReconciliationResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconciliation_result_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReconciliationResultId");

                    b.ToTable("reconciliation_lines", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.ReconciliationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DataHubTotalDkk")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("datahub_total_dkk");

                    b.Property<decimal>("DifferenceDkk")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("difference_dkk");

                    b.Property<decimal>("DifferencePercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("difference_percent");

                    b.Property<string>("GridArea")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grid_area");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<decimal>("OurTotalDkk")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("our_total_dkk");

                    b.Property<DateTimeOffset>("ReconciliationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reconciliation_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WholesaleSettlementId")
                        .HasColumnType("uuid")
                        .HasColumnName("wholesale_settlement_id");

                    b.HasKey("Id");

                    b.ToTable("reconciliation_results", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DocumentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("document_number")
                        .HasDefaultValueSql("nextval('settlement_document_seq')");

                    b.Property<string>("ExternalInvoiceReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_invoice_reference");

                    b.Property<DateTimeOffset?>("InvoicedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoiced_at");

                    b.Property<bool>("IsCorrection")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correction");

                    b.Property<Guid>("MeteringPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("metering_point_id");

                    b.Property<Guid?>("PreviousSettlementId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_settlement_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplyId")
                        .HasColumnType("uuid")
                        .HasColumnName("supply_id");

                    b.Property<Guid>("TimeSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_series_id");

                    b.Property<int>("TimeSeriesVersion")
                        .HasColumnType("integer")
                        .HasColumnName("time_series_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MeteringPointId");

                    b.HasIndex("Status");

                    b.HasIndex("SupplyId");

                    b.HasIndex("TimeSeriesId");

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SettlementIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("issue_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<Guid>("MeteringPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("metering_point_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TimeSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_series_id");

                    b.Property<int>("TimeSeriesVersion")
                        .HasColumnType("integer")
                        .HasColumnName("time_series_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeteringPointId");

                    b.HasIndex("Status");

                    b.HasIndex("MeteringPointId", "TimeSeriesId", "TimeSeriesVersion")
                        .IsUnique();

                    b.ToTable("settlement_issues", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SettlementLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("pris_id");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId");

                    b.ToTable("settlement_lines", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SpotPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PriceArea")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("price_area");

                    b.Property<decimal>("PriceDkkPerKwh")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("price_dkk_per_kwh");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PriceArea", "Timestamp")
                        .IsUnique();

                    b.ToTable("spot_prices", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SupplierIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("supplier_identities", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SupplierMargin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("PriceDkkPerKwh")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("price_dkk_per_kwh");

                    b.Property<Guid>("SupplierProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_product_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.HasKey("Id");

                    b.HasIndex("SupplierProductId", "ValidFrom")
                        .IsUnique();

                    b.ToTable("supplier_margins", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SupplierProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PricingModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("SpotAddon")
                        .HasColumnName("pricing_model");

                    b.Property<Guid>("SupplierIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_identity_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SupplierIdentityId", "Name")
                        .IsUnique();

                    b.ToTable("supplier_products", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Supply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_process_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("EndedByProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("ended_by_process_id");

                    b.Property<Guid>("MeteringPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("metering_point_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MeteringPointId");

                    b.ToTable("supplies", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SupplyProductPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SupplierProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_product_id");

                    b.Property<Guid>("SupplyId")
                        .HasColumnType("uuid")
                        .HasColumnName("supply_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SupplierProductId");

                    b.HasIndex("SupplyId", "SupplierProductId");

                    b.ToTable("supply_product_periods", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.TimeSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_latest");

                    b.Property<Guid>("MeteringPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("metering_point_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("resolution");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("MeteringPointId", "IsLatest");

                    b.ToTable("time_series", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.WholesaleSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("business_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("DKK")
                        .HasColumnName("currency");

                    b.Property<string>("GridArea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grid_area");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("resolution");

                    b.Property<decimal>("TotalAmountDkk")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount_dkk");

                    b.Property<decimal>("TotalEnergyKwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("total_energy_kwh");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("wholesale_settlements", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.WholesaleSettlementLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountDkk")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_dkk");

                    b.Property<string>("ChargeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("charge_id");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("charge_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("EnergyKwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("energy_kwh");

                    b.Property<string>("OwnerGln")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("owner_gln");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WholesaleSettlementId")
                        .HasColumnType("uuid")
                        .HasColumnName("wholesale_settlement_id");

                    b.HasKey("Id");

                    b.HasIndex("WholesaleSettlementId");

                    b.ToTable("wholesale_settlement_lines", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessProcess")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("business_process");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_processed");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("processing_attempts");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("processing_error");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ReceiverGln")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("receiver_gln");

                    b.Property<string>("SenderGln")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("sender_gln");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsProcessed");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessProcess")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("business_process");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sent");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("ReceiverGln")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("receiver_gln");

                    b.Property<string>("Response")
                        .HasColumnType("jsonb")
                        .HasColumnName("response");

                    b.Property<DateTimeOffset?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<int>("SendAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("send_attempts");

                    b.Property<string>("SendError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("send_error");

                    b.Property<string>("SenderGln")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("sender_gln");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsSent");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Processes.BrsProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_state");

                    b.Property<DateTimeOffset?>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("ProcessData")
                        .HasColumnType("jsonb")
                        .HasColumnName("process_data");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("process_type");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId");

                    b.ToTable("brs_processes", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Processes.ProcessStateTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("from_state");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("to_state");

                    b.Property<DateTimeOffset>("TransitionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transitioned_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("process_state_transitions", (string)null);
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.AggregatedObservation", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.AggregatedTimeSeries", null)
                        .WithMany("Observations")
                        .HasForeignKey("AggregatedTimeSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.AggregatedTimeSeries", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "Period", b1 =>
                        {
                            b1.Property<Guid>("AggregatedTimeSeriesId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_start");

                            b1.HasKey("AggregatedTimeSeriesId");

                            b1.ToTable("aggregated_time_series");

                            b1.WithOwner()
                                .HasForeignKey("AggregatedTimeSeriesId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Customer", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.SupplierIdentity", "SupplierIdentity")
                        .WithMany()
                        .HasForeignKey("SupplierIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("building_number");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city_name");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("Floor")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("floor");

                            b1.Property<string>("MunicipalityCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("municipality_code");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("post_code");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street_name");

                            b1.Property<string>("Suite")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("suite");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.CvrNumber", "Cvr", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("cvr");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.CprNumber", "Cpr", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("cpr");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Cpr");

                    b.Navigation("Cvr");

                    b.Navigation("SupplierIdentity");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.MeteringPoint", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("MeteringPointId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("building_number");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city_name");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("Floor")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("floor");

                            b1.Property<string>("MunicipalityCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("municipality_code");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("post_code");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street_name");

                            b1.Property<string>("Suite")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("suite");

                            b1.HasKey("MeteringPointId");

                            b1.ToTable("metering_points");

                            b1.WithOwner()
                                .HasForeignKey("MeteringPointId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.GlnNumber", "GridCompanyGln", b1 =>
                        {
                            b1.Property<Guid>("MeteringPointId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("character varying(13)")
                                .HasColumnName("grid_company_gln");

                            b1.HasKey("MeteringPointId");

                            b1.ToTable("metering_points");

                            b1.WithOwner()
                                .HasForeignKey("MeteringPointId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Gsrn", "Gsrn", b1 =>
                        {
                            b1.Property<Guid>("MeteringPointId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(18)
                                .HasColumnType("character varying(18)")
                                .HasColumnName("gsrn");

                            b1.HasKey("MeteringPointId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("metering_points");

                            b1.WithOwner()
                                .HasForeignKey("MeteringPointId");
                        });

                    b.Navigation("Address");

                    b.Navigation("GridCompanyGln")
                        .IsRequired();

                    b.Navigation("Gsrn")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Observation", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.TimeSeries", null)
                        .WithMany("Observations")
                        .HasForeignKey("TimeSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.EnergyQuantity", "Quantity", b1 =>
                        {
                            b1.Property<DateTimeOffset>("ObservationTimestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("ObservationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasDefaultValue("kWh")
                                .HasColumnName("quantity_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("quantity_kwh");

                            b1.HasKey("ObservationTimestamp", "ObservationId");

                            b1.ToTable("observations");

                            b1.WithOwner()
                                .HasForeignKey("ObservationTimestamp", "ObservationId");
                        });

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Price", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.GlnNumber", "OwnerGln", b1 =>
                        {
                            b1.Property<Guid>("PriceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("character varying(13)")
                                .HasColumnName("owner_gln");

                            b1.HasKey("PriceId");

                            b1.ToTable("prices");

                            b1.WithOwner()
                                .HasForeignKey("PriceId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "ValidityPeriod", b1 =>
                        {
                            b1.Property<Guid>("PriceId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_to");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_from");

                            b1.HasKey("PriceId");

                            b1.ToTable("prices");

                            b1.WithOwner()
                                .HasForeignKey("PriceId");
                        });

                    b.Navigation("OwnerGln")
                        .IsRequired();

                    b.Navigation("ValidityPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.PriceLink", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.MeteringPoint", "MeteringPoint")
                        .WithMany()
                        .HasForeignKey("MeteringPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WattsOn.Domain.Entities.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "LinkPeriod", b1 =>
                        {
                            b1.Property<Guid>("PriceLinkId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("link_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("link_start");

                            b1.HasKey("PriceLinkId");

                            b1.ToTable("price_links");

                            b1.WithOwner()
                                .HasForeignKey("PriceLinkId");
                        });

                    b.Navigation("LinkPeriod")
                        .IsRequired();

                    b.Navigation("MeteringPoint");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.PricePoint", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Price", null)
                        .WithMany("PricePoints")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.ReconciliationLine", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.ReconciliationResult", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReconciliationResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.ReconciliationResult", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "Period", b1 =>
                        {
                            b1.Property<Guid>("ReconciliationResultId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_start");

                            b1.HasKey("ReconciliationResultId");

                            b1.ToTable("reconciliation_results");

                            b1.WithOwner()
                                .HasForeignKey("ReconciliationResultId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Settlement", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.MeteringPoint", "MeteringPoint")
                        .WithMany()
                        .HasForeignKey("MeteringPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WattsOn.Domain.Entities.Supply", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WattsOn.Domain.Entities.TimeSeries", "TimeSeries")
                        .WithMany()
                        .HasForeignKey("TimeSeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "SettlementPeriod", b1 =>
                        {
                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("settlement_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("settlement_start");

                            b1.HasKey("SettlementId");

                            b1.ToTable("settlements");

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("DKK")
                                .HasColumnName("total_currency");

                            b1.HasKey("SettlementId");

                            b1.ToTable("settlements");

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.EnergyQuantity", "TotalEnergy", b1 =>
                        {
                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasDefaultValue("kWh")
                                .HasColumnName("total_energy_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("total_energy_kwh");

                            b1.HasKey("SettlementId");

                            b1.ToTable("settlements");

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");
                        });

                    b.Navigation("MeteringPoint");

                    b.Navigation("SettlementPeriod")
                        .IsRequired();

                    b.Navigation("Supply");

                    b.Navigation("TimeSeries");

                    b.Navigation("TotalAmount")
                        .IsRequired();

                    b.Navigation("TotalEnergy")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SettlementIssue", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "Period", b1 =>
                        {
                            b1.Property<Guid>("SettlementIssueId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_start");

                            b1.HasKey("SettlementIssueId");

                            b1.ToTable("settlement_issues");

                            b1.WithOwner()
                                .HasForeignKey("SettlementIssueId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SettlementLine", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Settlement", null)
                        .WithMany("Lines")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("SettlementLineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("DKK")
                                .HasColumnName("amount_currency");

                            b1.HasKey("SettlementLineId");

                            b1.ToTable("settlement_lines");

                            b1.WithOwner()
                                .HasForeignKey("SettlementLineId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.EnergyQuantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("SettlementLineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasDefaultValue("kWh")
                                .HasColumnName("quantity_unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("quantity_kwh");

                            b1.HasKey("SettlementLineId");

                            b1.ToTable("settlement_lines");

                            b1.WithOwner()
                                .HasForeignKey("SettlementLineId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SupplierIdentity", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.CvrNumber", "Cvr", b1 =>
                        {
                            b1.Property<Guid>("SupplierIdentityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("cvr");

                            b1.HasKey("SupplierIdentityId");

                            b1.ToTable("supplier_identities");

                            b1.WithOwner()
                                .HasForeignKey("SupplierIdentityId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.GlnNumber", "Gln", b1 =>
                        {
                            b1.Property<Guid>("SupplierIdentityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("character varying(13)")
                                .HasColumnName("gln");

                            b1.HasKey("SupplierIdentityId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("supplier_identities");

                            b1.WithOwner()
                                .HasForeignKey("SupplierIdentityId");
                        });

                    b.Navigation("Cvr");

                    b.Navigation("Gln")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SupplierMargin", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.SupplierProduct", "SupplierProduct")
                        .WithMany()
                        .HasForeignKey("SupplierProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SupplierProduct");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SupplierProduct", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.SupplierIdentity", "SupplierIdentity")
                        .WithMany()
                        .HasForeignKey("SupplierIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SupplierIdentity");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Supply", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.Customer", "Customer")
                        .WithMany("Supplies")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WattsOn.Domain.Entities.MeteringPoint", "MeteringPoint")
                        .WithMany("Supplies")
                        .HasForeignKey("MeteringPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "SupplyPeriod", b1 =>
                        {
                            b1.Property<Guid>("SupplyId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("supply_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("supply_start");

                            b1.HasKey("SupplyId");

                            b1.ToTable("supplies");

                            b1.WithOwner()
                                .HasForeignKey("SupplyId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("MeteringPoint");

                    b.Navigation("SupplyPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.SupplyProductPeriod", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.SupplierProduct", "SupplierProduct")
                        .WithMany()
                        .HasForeignKey("SupplierProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WattsOn.Domain.Entities.Supply", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "Period", b1 =>
                        {
                            b1.Property<Guid>("SupplyProductPeriodId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_start");

                            b1.HasKey("SupplyProductPeriodId");

                            b1.ToTable("supply_product_periods");

                            b1.WithOwner()
                                .HasForeignKey("SupplyProductPeriodId");
                        });

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("SupplierProduct");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.TimeSeries", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.MeteringPoint", "MeteringPoint")
                        .WithMany("TimeSeriesCollection")
                        .HasForeignKey("MeteringPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "Period", b1 =>
                        {
                            b1.Property<Guid>("TimeSeriesId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_start");

                            b1.HasKey("TimeSeriesId");

                            b1.ToTable("time_series");

                            b1.WithOwner()
                                .HasForeignKey("TimeSeriesId");
                        });

                    b.Navigation("MeteringPoint");

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.WholesaleSettlement", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.Period", "Period", b1 =>
                        {
                            b1.Property<Guid>("WholesaleSettlementId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_start");

                            b1.HasKey("WholesaleSettlementId");

                            b1.ToTable("wholesale_settlements");

                            b1.WithOwner()
                                .HasForeignKey("WholesaleSettlementId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.WholesaleSettlementLine", b =>
                {
                    b.HasOne("WattsOn.Domain.Entities.WholesaleSettlement", null)
                        .WithMany("Lines")
                        .HasForeignKey("WholesaleSettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Processes.BrsProcess", b =>
                {
                    b.OwnsOne("WattsOn.Domain.ValueObjects.GlnNumber", "CounterpartGln", b1 =>
                        {
                            b1.Property<Guid>("BrsProcessId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("character varying(13)")
                                .HasColumnName("counterpart_gln");

                            b1.HasKey("BrsProcessId");

                            b1.ToTable("brs_processes");

                            b1.WithOwner()
                                .HasForeignKey("BrsProcessId");
                        });

                    b.OwnsOne("WattsOn.Domain.ValueObjects.Gsrn", "MeteringPointGsrn", b1 =>
                        {
                            b1.Property<Guid>("BrsProcessId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(18)
                                .HasColumnType("character varying(18)")
                                .HasColumnName("metering_point_gsrn");

                            b1.HasKey("BrsProcessId");

                            b1.ToTable("brs_processes");

                            b1.WithOwner()
                                .HasForeignKey("BrsProcessId");
                        });

                    b.Navigation("CounterpartGln");

                    b.Navigation("MeteringPointGsrn");
                });

            modelBuilder.Entity("WattsOn.Domain.Processes.ProcessStateTransition", b =>
                {
                    b.HasOne("WattsOn.Domain.Processes.BrsProcess", null)
                        .WithMany("Transitions")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.AggregatedTimeSeries", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Supplies");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.MeteringPoint", b =>
                {
                    b.Navigation("Supplies");

                    b.Navigation("TimeSeriesCollection");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Price", b =>
                {
                    b.Navigation("PricePoints");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.ReconciliationResult", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.Settlement", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.TimeSeries", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("WattsOn.Domain.Entities.WholesaleSettlement", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("WattsOn.Domain.Processes.BrsProcess", b =>
                {
                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
